services:
    MikeAmelung\CranialBundle\Utils\Markdown:
    MikeAmelung\CranialBundle\Controller\:
        resource: "../../Controller"
        tags: ["controller.service_arguments"]
    MikeAmelung\CranialBundle\Twig\CranialExtension:
        arguments: ['@MikeAmelung\CranialBundle\Utils\Markdown']
        tags: ["twig.extension"]
    MikeAmelung\CranialBundle\Service\ContentManager:
        arguments:
            $configDirectory: "%mike_amelung_cranial.config_directory%"
            $contentDirectory: "%mike_amelung_cranial.content_directory%"
            $imageProcessor: '@MikeAmelung\CranialBundle\Service\ImageProcessor'
            $storage: "%mike_amelung_cranial.storage%"
            $twig: "@twig"
            $em: "@doctrine.orm.default_entity_manager"
    MikeAmelung\CranialBundle\Service\ImageProcessor:
        arguments:
            $imageDirectory: "%mike_amelung_cranial.image_directory%"
            $imagePathPrefix: "%mike_amelung_cranial.image_path_prefix%"
    MikeAmelung\CranialBundle\Command\DupeContentCommand:
        arguments:
            $contentManager: '@MikeAmelung\CranialBundle\Service\ContentManager'
        tags: ["console.command"]
    MikeAmelung\CranialBundle\Command\GenerateThumbnailsCommand:
        arguments:
            $contentManager: '@MikeAmelung\CranialBundle\Service\ContentManager'
        tags: ["console.command"]
    MikeAmelung\CranialBundle\Command\ScanImagesCommand:
        arguments:
            $contentManager: '@MikeAmelung\CranialBundle\Service\ContentManager'
            $imageDirectory: "%mike_amelung_cranial.image_directory%"
        tags: ["console.command"]
