services:
    MikeAmelung\CranialBundle\Utils\Markdown:
    MikeAmelung\CranialBundle\Controller\:
        resource: "../../Controller"
        tags: ["controller.service_arguments"]
    MikeAmelung\CranialBundle\Twig\CranialExtension:
        arguments: ['@MikeAmelung\CranialBundle\Utils\Markdown']
        tags: ["twig.extension"]
    MikeAmelung\CranialBundle\ContentManager\ContentManager:
        arguments:
            $configDirectory: "%mike_amelung_cranial.config_directory%"
            $fileProcessor: "@mike_amelung_cranial.file_processor"
            $imageProcessor: "@mike_amelung_cranial.image_processor"
            $storage: "@mike_amelung_cranial.storage"
            $twig: "@twig"
    MikeAmelung\CranialBundle\Command\DupeContentCommand:
        arguments:
            $contentManager: '@MikeAmelung\CranialBundle\ContentManager\ContentManager'
        tags: ["console.command"]
    MikeAmelung\CranialBundle\Command\GenerateThumbnailsCommand:
        arguments:
            $contentManager: '@MikeAmelung\CranialBundle\ContentManager\ContentManager'
        tags: ["console.command"]
    MikeAmelung\CranialBundle\Command\ScanImagesCommand:
        arguments:
            $contentManager: '@MikeAmelung\CranialBundle\ContentManager\ContentManager'
            $imageProcessor: "@mike_amelung_cranial.image_processor"
        tags: ["console.command"]
